In [14]:
# Memanggil dataset iris
from sklearn.datasets import load_iris
iris_ku = load_iris()

# simpan data fitur/kolom (x) dan target (y)
x = iris_ku.data
y = iris_ku.target

# simpan nama fitur/kolom (x) dan target (y)
feature_names = iris_ku.feature_names
target_names = iris_ku.target_names

# tampil nama fitur dan target data set
print("Feature names :", feature_names)
print("Target names :", target_names)

# x dan y adalah numpy arrays
print("\n Type of X is : ", type(x))

# tampilkan 5 baris pertama
print("\n First 5 rows of x: \n", x[:5])

# fitur (x) and target (y)
x = iris_ku.data
y = iris_ku.target

# splitting x dan y untuk data latih dan uji
from sklearn.model_selection import train_test_split 
x_latih, x_tes, y_latih, y_tes = train_test_split(x, y, test_size=0.4, random_state=1)

# tampilkan data fitur latih dan uji
print(x_latih.shape)
print(x_tes.shape)

# tampilkan data target latih dan uji
print(y_latih.shape)
print(y_tes.shape)

# pelatihan pada data latih menggunakan KNN (k=3)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(x_latih, y_latih)

# melakukan  prediksi pada data uji
y_prediksi = knn.predict(x_tes)
pred_species2 = [iris_ku.target_names[p] for p in y_prediksi]
print("Prediksi :", pred_species2)

# perbandingan nilai aktual (y_tes) dengan nilai prediksi (y_prediksi)
from sklearn import metrics
print("Akurasi model KNN :", metrics.accuracy_score(y_tes, y_prediksi))

# prediksi menggunakan data sample buatan sendiri
contoh = [[3,5,4,2], [2,3,5,4]]
preds = knn.predict(contoh)
pred_species = [iris_ku.target_names[p] for p in preds]
print("Prediksi :", pred_species)

# saving the model
import joblib
joblib.dump(knn, 'iris_knn.pkl')

Feature names : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names : ['setosa' 'versicolor' 'virginica']

 Type of X is :  <class 'numpy.ndarray'>

 First 5 rows of x: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
(90, 4)
(60, 4)
(90,)
(60,)
Prediksi : ['setosa', 'versicolor', 'versicolor', 'setosa', 'virginica', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor', 'setosa', 'versicolor', 'versicolor', 'setosa', 'setosa', 'versicolor', 'versicolor', 'virginica', 'setosa', 'virginica', 'versicolor', 'setosa', 'setosa', 'versicolor', 'virginica', 'versicolor', 'virginica', 'versicolor', 'virginica', 'virginica', 'setosa', 'versicolor', 'setosa', 'versicolor', 'virginica', 'virginica', 'setosa', 'virginica', 'virginica', 'versicolor', 'virginica', 'setosa', 'setosa', 'setosa', 'versicolor', 'setosa', 'setosa', 'virginica',

['iris_knn.pkl']

In [15]:
# Memanggil dataset iris
from sklearn.datasets import load_iris
iris_ku = load_iris()

# simpan data fitur/kolom (x) dan target (y)
x = iris_ku.data
y = iris_ku.target

# fitur (x) and target (y)
x = iris_ku.data
y = iris_ku.target

# splitting x dan y untuk data latih dan uji
from sklearn.model_selection import train_test_split 
x_latih, x_tes, y_latih, y_tes = train_test_split(x, y, test_size=0.4, random_state=1)

# pelatihan pada data latih menggunakan KNN (k=3)
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_latih, y_latih)

# melakukan  prediksi pada data uji
y_prediksi = knn.predict(x_tes)
pred_species2 = [iris_ku.target_names[p] for p in y_prediksi]
print("Prediksi :", pred_species2)

from sklearn import metrics
print("Akurasi model KNN :", metrics.accuracy_score(y_tes, y_prediksi))

Prediksi : ['setosa', 'versicolor', 'versicolor', 'setosa', 'virginica', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor', 'setosa', 'versicolor', 'versicolor', 'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor', 'setosa', 'virginica', 'versicolor', 'setosa', 'setosa', 'versicolor', 'virginica', 'versicolor', 'virginica', 'versicolor', 'virginica', 'virginica', 'setosa', 'versicolor', 'setosa', 'versicolor', 'virginica', 'virginica', 'setosa', 'versicolor', 'virginica', 'versicolor', 'virginica', 'setosa', 'setosa', 'setosa', 'versicolor', 'setosa', 'setosa', 'virginica', 'virginica', 'virginica', 'virginica', 'virginica', 'versicolor', 'virginica', 'versicolor']
Akurasi model KNN : 0.9833333333333333


In [16]:
# Memanggil dataset iris
from sklearn.datasets import load_iris
iris_ku = load_iris()

# simpan data fitur/kolom (x) dan target (y)
x = iris_ku.data
y = iris_ku.target

# fitur (x) and target (y)
x = iris_ku.data
y = iris_ku.target

# splitting x dan y untuk data latih dan uji
from sklearn.model_selection import train_test_split 
x_latih, x_tes, y_latih, y_tes = train_test_split(x, y, test_size=0.4, random_state=1)

# pelatihan pada data latih menggunakan KNN (k=5,7,10,21)
from sklearn.neighbors import KNeighborsClassifier
k = [5, 7, 10, 21]
for i in k:
    knn = KNeighborsClassifier(n_neighbors=i)

    knn.fit(x, y)

    akurasi = knn.score(x_tes, y_tes)

    print(f"Akurasi model KNN K:{i} = {akurasi}")

Akurasi model KNN K:5 = 0.9833333333333333
Akurasi model KNN K:7 = 1.0
Akurasi model KNN K:10 = 1.0
Akurasi model KNN K:21 = 0.9833333333333333


## **Rumus Manhattan**

In [17]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
predikat = pd.read_csv("Lokasi.csv")
x = predikat.drop(["Rumah", "Lokasi"], axis=1)
y = predikat["Lokasi"]
# Membuat KNN Classifier
knn = KNeighborsClassifier(n_neighbors=3, metric='manhattan')

# Menguji model menggunakan data training 
knn.fit(x, y)

dataLatih = [[10, 15]]
prediction = knn.predict(dataLatih)
distances, indices = knn.kneighbors(dataLatih)
for i in range(len(dataLatih)):
    print(f"Data baru: {dataLatih[i]}")
    for j in range(len(distances[i])):
        idx = indices[i][j]
        print(f"Ranking ke-{j+1}: Jarak = {distances[i][j]}, Rumah = {predikat.loc[idx,'Rumah']}, Data = {y.loc[idx]}")

Data baru: [10, 15]
Ranking ke-1: Jarak = 12.0, Rumah = A, Data = Kota
Ranking ke-2: Jarak = 17.0, Rumah = E, Data = Kota
Ranking ke-3: Jarak = 19.0, Rumah = B, Data = Kota


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


# **Rumus Minkowski**

In [18]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
predikat = pd.read_csv("Lokasi.csv")
x = predikat.drop(["Rumah", "Lokasi"], axis=1)
y = predikat["Lokasi"]
# Membuat KNN Classifier
knn = KNeighborsClassifier(n_neighbors=3, metric='minkowski')

# Menguji model menggunakan data training 
knn.fit(x, y)

dataLatih = [[10, 15]]
prediction = knn.predict(dataLatih)
distances, indices = knn.kneighbors(dataLatih)
for i in range(len(dataLatih)):
    print(f"Data baru: {dataLatih[i]}")
    for j in range(len(distances[i])):
        idx = indices[i][j]
        print(f"Ranking ke-{j+1}: Jarak = {distances[i][j]}, Rumah = {predikat.loc[idx,'Rumah']}, Data = {y.loc[idx]}")

Data baru: [10, 15]
Ranking ke-1: Jarak = 11.045361017187261, Rumah = A, Data = Kota
Ranking ke-2: Jarak = 12.529964086141668, Rumah = E, Data = Kota
Ranking ke-3: Jarak = 14.212670403551895, Rumah = H, Data = Kabupaten


/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
